sjlist/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  root 'categories#index'

  resources :users
  resources :categories do
    resources :posts, only: [:index, :show, :new]
  end

  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

end

sjlist/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  validates :name, length: {minimum: 2}, uniqueness: true
end

sjlist/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :author, class_name: "User"
  validates :author, presence: true
  belongs_to :category
  validates :category, presence: true
  validates :body, length: { minimum: 10 }
end

sjlist/app/models/user.rb
class User < ActiveRecord::Base
  # include BCrypt
  has_secure_password
  validates :name, presence: true
  validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/, message: "must be a valid email address"},
                    uniqueness: {message: "already taken"}
  # validate :password_is_strong
  has_many :posts, foreign_key: :author_id
  validates :password, length: { minimum: 8 }

  # def password
  #   @password = Password.new(encrypted_password)
  # end

  # def password_is_strong
  #   if @proposed_password.length < 8
  #     errors.add(:password, "must be at least 8 chars long")
  #   end
  # end

  # def password=(new_password)
  #   @proposed_password = new_password
  #   @password = Password.create(new_password)
  #   self.encrypted_password = @password
  # end

  # def authenticate(password)
  #   self.password == password
  # end
end

sjlist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # include ApplicationHelper

  # helper_method :current_user, :logged_in?

  # def current_user
  #   @current_user ||= User.find_by(id: session[:user])
  # end

  # def logged_in?
  #   current_user != nil
  # end

end

sjlist/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ApplicationHelper
  def index
    @categories = Category.order(:name)
  end

  def show
    @category = Category.find_by(id: params[:id])
    @posts = @category.posts.order(updated_at: :desc)
  end
end

sjlist/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  def index
    if params[:category_id]
      @category = Category.find_by(id: params[:category_id])
      @posts = @category.posts.order(updated_at: :desc)
    else
      @posts = Post.order(updated_at: :desc)
    end
  end

  def new
    @post = Post.new
    if params[:category_id]
      @category = Category.find_by(id: params[:category_id])
    end
  end

  def create
    if logged_in?
      @post = Post.new(post_params)
      @post.author = current_user
      if params[:category_id]
        @category = Category.find_by(id: params[:category_id])
      end
      if @post.save
        redirect_to @post
      else
        @errors = @post.errors.full_messages
        render :new
      end
    else
      @errors = ["You are not logged in"]
      render 'sessions/new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    if logged_in?
      @post = Post.find(params[:id])
      if current_user == @post.author
        @category = @post.category
        render :edit
      else
        @errors = ["You are not the creator of this..."]
        redirect_to @post
      end
    else
      @errors = ["You are not logged in"]
      render 'sessions/new'
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if logged_in?
      if @post.author == current_user
        if @post.update_attributes(post_params)
          redirect_to @post
        else
          @errors = @post.errors.full_messages
          render :edit
        end
      else
        @errors = ["naughty naughty"]
        render :show
      end
    else
      redirect_to @post
    end
  end

  def destroy
    if logged_in?
      @post = Post.find_by(id: params[:id])
      if @post
        if current_user == @post.author
          @post.destroy
          # change this to category index when created
          redirect_to @post.category
        else
          @errors = ["You are not the creator of this..."]
          redirect_to @post
        end
      else
        redirect_to categories_url
      end
    else
      @errors = ["You are not logged in"]
      render 'sessions/new'
    end
  end


  private
  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

end

sjlist/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new unless @user
  end

  def create
    @user = User.find_by(email: session_params[:email])
    if @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to :root
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end

  private
  def session_params
    params.require(:session).permit :email, :password
  end

end

sjlist/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new unless @user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :root
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end


  private
  def user_params
    params.require(:user).permit :name, :email, :password
  end

end

sjlist/app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def pretty_time(time_stamp)
    time_stamp.strftime("%B %-m, %Y %H:%M")
  end

end

sjlist/app/views/application/_errors.html.erb
<% if @errors %>
<div class="errors">Errors:
  <% @errors.each do |error| %>
  <p><%= error %></p>
  <% end %>
</div>
<% end %>

sjlist/app/views/categories/index.html.erb
<h2>Categories:</h2>
<% if @categories.any? %>
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
<% end %>

sjlist/app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<% if @posts.any? %>
  <ul class="posts">
    <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'New Post', new_category_post_path(@category) %>
<%= link_to 'All Categories', categories_path %>

sjlist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sjlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <%= link_to 'Logout', sessions_url, method: :delete %>
<% else %>
  <%= link_to 'New User', new_user_url %>
  <%= link_to 'Login', sessions_new_url %>
<% end %>

<%= yield %>

</body>
</html>

sjlist/app/views/posts/edit.html.erb
<h1>Edit Post:</h1>

<%= render 'errors' %>

<%= form_for :post, url: post_path, method: :patch do |f| %>
  <p>
    <%= f.label :category_id %><br />
    <% if @category %>
      <%= f.collection_select(:category_id, Category.order(:name), :id, :name, {selected: @category.id}) %>
    <% else %>
      <%= f.collection_select(:category_id, Category.order(:name), :id, :name, {include_blank: true}) %>
    <% end %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Edit" %>
  </p>
<% end %>
<%= link_to 'Back', :post %>

sjlist/app/views/posts/index.html.erb
<h1>Posts: </h1>
<% if @posts.any? %>
<ul class="posts">
  <% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>
<% end %>

<% if params[:category_id] %>
<%= link_to 'New Post', new_category_post_path(@category) %>
<% else %>
<%= link_to 'New Post', new_post_url %>
<% end %>

sjlist/app/views/posts/new.html.erb
<h1>New Post:</h1>

<%= render 'errors' %>

<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :category_id %><br />
    <% if @category %>
      <%= f.collection_select(:category_id, Category.order(:name), :id, :name, {selected: @category.id}) %>
    <% else %>
      <%= f.collection_select(:category_id, Category.order(:name), :id, :name, {include_blank: true}) %>
    <% end %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>
<%= link_to 'Back', posts_path %>

sjlist/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Posted by: <%= @post.author.name %></p>
<p>Category: <%= @post.category.name %></p>
<p>Description:</p>
<p><%= @post.body %></p>
<p>Posted at: <%= pretty_time(@post.created_at) %></p>

<% if @post.author == current_user %>
<%= link_to 'Edit', edit_post_url %>
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
<% end %>
<%= link_to 'Back', category_path(@post.category) %>

sjlist/app/views/users/new.html.erb
<h1>New User:</h1>

<%= render 'errors' %>

<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>
<%= link_to 'Back', posts_path %>